### ISSUE TITLE
Support start value other than 1. for enumerations

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#13] opened 2017-05-01 09:27 UTC
HTML has `start` attribute for `ol` lists. It can change starting value for lists. It is useful, for example, when lists are broken into parts with headings.

I have checked, [original Muse](http://repo.or.cz/w/muse-el.git) does not support it, and even if list starts with `2.`, it is converted to `<ol>` tag(see [muse-html.el](http://repo.or.cz/muse-el.git/blob/caaa41cbf959afb379516e88776ec374160b8a94:/lisp/muse-html.el#l315)) not `<ol start=2>`. Still, I think it can be a useful extension.

How about determining starting value from prefix [when list is detected](https://github.com/melmothx/text-amuse/blob/01af46cc07bd37d14c22ade5bd0eef1a55a67cd2/lib/Text/Amuse/Document.pm#L531) and adding `start` attribute if it is not 1?

**Comment by melmothx** [comment] 2017-05-03 06:23
It looks doable. I need to check how would work with LaTeX though.

**Comment by labdsf** [comment] 2017-05-03 08:15
In LaTeX it is also possible: https://tex.stackexchange.com/questions/142/how-can-i-make-an-enumerate-list-start-at-something-other-than-1

**Comment by melmothx** [comment] 2017-05-03 08:48
This would require switching from the `enumerate` package to `enumitem` which gives more flexibility as well, but needs careful testing.

**Comment by labdsf** [comment] 2017-05-03 09:38
@melmothx No, `enumerate` is enough, see [the first answer](https://tex.stackexchange.com/a/149).

**Comment by melmothx** [comment] 2017-05-03 10:53
Alexander Krotov <notifications@github.com> writes:

> @melmothx No, enumerate is enough, see the first answer.

First answer needs too much hacking and the nesting level needs to be
tracked. Lists (because of the nesting) are the most convolute region of
the code, and adding something like that looks wrong, while an attribute
on the environment would be much better.

-- 
Marco

**Comment by melmothx** [comment] 2017-05-03 10:59
@labdsf mind to post a LaTeX sample produced by pandoc with nested lists starting at random index and random type?

**Comment by labdsf** [comment] 2017-05-03 12:05
Input
```
2. First

3. Second

    7. Third

    8. Abc

c. First

d. Second

    f. Third

    g. Abc
```

Output
```
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  First
\item
  Second

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \setcounter{enumii}{6}
  \item
    Third
  \item
    Abc
  \end{enumerate}
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\item
  First
\item
  Second

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \setcounter{enumii}{5}
  \item
    Third
  \item
    Abc
  \end{enumerate}
\end{enumerate}
```

**Comment by melmothx** [comment] 2017-05-03 12:41
Thanks. I'll mumble a bit about this whole issue and hopefully come back with some working code. Thanks so far!

**Comment by melmothx** [comment] 2017-08-03 12:10
I've been mumbling about this issue for a while, and I don't think it's good idea after all, because if we support this, there is no reason why we shouldn't support a list like 1. 2. 5. 6. obeying the indexes. On the other hand, we already clearly state that we renumber them, so 1. 1. 1. will turn to 1. 2. 3.

On the other hand, such custom lists could make use of the description lists, like 2) :: item 4) :: item and have a decent output.

**Comment by melmothx** [comment] 2017-08-03 12:11
As another note, it would be interesting to have a real-world user case. I.e., somebody really needing this feature. I'm not prone to add features which creates more backward-compatibility issues than they solve.

**Comment by labdsf** [comment] 2017-08-03 16:08
@melmothx 
> As another note, it would be interesting to have a real-world user case. I.e., somebody really needing this feature.

As I wrote in the first post
> It is useful, for example, when lists are broken into parts with headings.

I have seen a document that was a huge list itself (something like a list of rules or a contract), which was broken into parts by headers. Because of headers it cannot be one continuous list, so each item was an unintended paragraph instead. Actually that is why I opened this issue.

**Comment by melmothx** [comment] 2017-08-03 16:52
Alexander Krotov <notifications@github.com> writes:

> @melmothx 
>> As another note, it would be interesting to have a real-world user case. I.e., somebody really needing this feature.
>
> As I wrote in the first post
>> It is useful, for example, when lists are broken into parts with headings.
>
> I have seen a document that was a huge list itself (something like a
> list of rules or a contract), which was broken into parts by headers.
> Because of headers it cannot be one continuous list, so each item was
> an unintended paragraph instead. Actually that is why I opened this
> issue.

Ok, makes sense.

-- 
Marco

**Comment by melmothx** [comment] 2017-08-26 15:40
This is mostly done but still needs the handling of list resuming at i. v. l. x. which can be as well a roman list + some serious testing + doc update (note to self).

**Comment by melmothx** [comment] 2017-08-28 17:17
@labdsf I guess the current enumerations-start-index branch is the best it can get without a full reparse (and code rewriting) of lists. Say the sequence i. .l m. In a perfect world, we could scan the list, reach the "l", understand it's and alpha, go back and change the type of the previous element. However, the current code interprets "i" as roman, index 1. Then see "l" as a roman as well, then start a new list on the same level with index 50. Then see m, and start an alpha list. The illusion is perfect, but basically they are 3 lists on the same level, not one. The problem is where alpha and roman lists overlaps, obviously. I kind of think it's good enough, though.

As a side effect, if you number 1.  1. 1., it's fine. If you put random numbers, the list reset and obey the index. Which is an improvement for sure.

**Comment by labdsf** [comment] 2017-08-28 19:09
FYI Emacs Muse doesn't support alpha lists, I just checked it. Anyway, an alpha list starting with `I.` is very unlikely.

**Comment by melmothx** [comment] 2017-08-30 13:46
This looks done to me. I've release 0.90 on CPAN. A .deb package will be released with the next amusewiki upgrade.

**Closed by melmothx** 2017-08-30 13:46 UTC
