### ISSUE TITLE
Table parser accepts incorrect markup

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#14] opened 2017-05-07 22:32 UTC
`muse-compile.pl` produces a table from the following file:
```
#title ok

 First|Second
```

Original Muse accepts `|` as field separator only if it is surrounded by spaces according to [regexp](https://github.com/alexott/muse/blob/0bb5d3fa57bfc876bacec732a0c1d8f796942403/lisp/muse-regexps.el#L180). I also checked it with Emacs, the minimal example that works is `First | Second`, not `First| Second` or ` First |Second`.

**Comment by labdsf** [comment] 2017-05-07 22:35
Also, original Muse does not require tables to be indented with a space. Accidental tables don't happen because separators are surrounded by spaces.

**Comment by melmothx** [comment] 2017-05-08 06:31
Alexander Krotov <notifications@github.com> writes:

> Also, original Muse does not require tables to be indented with a
> space. Accidental tables don't happen because separators are
> surrounded by spaces.

Thanks for the report. I'm looking into it and will get fixed ASAP.

-- 
Marco

**Comment by melmothx** [comment] 2017-08-03 13:03
I've grepped the archives I know of, and a lonely `|` could still happen. I have this case: `[[http://example.org][Site Name | Slogan]]`

Now, the problem is that Emacs Muse doesn't define in the manual exactly this thing. Now, for the pandoc writer, I guess if you indent and surround by space, you get a .muse which is compatible to both implementation and it's also more pleasant to look at (with indentation you spot it more easily, e.g. if you have a lot of text packed in there).

For the reader, I guess that you could trigger the table as well in both cases, and get a sensible parsing. Although if you have inline code in the document, this pipe is likely to appear often.

Thoughts?

**Comment by melmothx** [comment] 2017-11-28 17:36
@labdsf ping on this one.

**Comment by labdsf** [comment] 2017-12-19 01:43
That is how I did it. It makes sense for me to unify parsing as much as possible. On the other hand it will break backwards compatibility for existing Amusewiki installations.

Probably the best way is to close this and add "differences from Emacs Muse" section to markup manual.

**Comment by melmothx** [comment] 2017-12-27 15:10
Closed by https://github.com/melmothx/amusewiki-site/commit/6669fca220bd8280fb0173001e78d31128fa879a

**Closed by melmothx** 2017-12-27 15:10 UTC
